on: push
name: Test, Build and Release apk
jobs:
  build:
    name: Build APK
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    # - uses: dart-lang/setup-dart@v1.0
    #  with:
    #      sdk: '2.13.4'
    - uses: subosito/flutter-action@v1.5.3
      with:
        flutter-version: '2.2.3'
    - name : flutter pub get
      working-directory: ./src
      run: flutter pub get
    - name: Setting key
      env:
          ENCODED_KEYSTORE: ${{ secrets.ENCODED_KEYSTORE }}
      working-directory: ./src
      run: echo $ENCODED_KEYSTORE | base64 --decode > android/app/key.jks
    - name : flutter build apk
      working-directory: ./src
      env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD}}
      run: flutter build apk  --debug --split-per-abi
    - name : flutter build ios --release --no-codesign
      working-directory: ./src
      run : flutter build ios --debug --no-codesign
    - name: Push APK to Releases
      uses: ncipollo/release-action@v1
      with:
        working-directory: ./src
        tag: "${{ steps.release_tag.outputs.new_tag }}"
        artifacts: "build/app/outputs/apk/debug/*.apk"
        token: ${{ secrets.RELEASE_TOKEN }}
