on: push
name: Test, Build and Release apk
jobs:
  build:
    name: Build APK
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    # - uses: dart-lang/setup-dart@v1.0
    #  with:
    #      sdk: '2.13.4'
    - uses: subosito/flutter-action@v1.5.3
      with:
        flutter-version: '2.2.3'
    - name : flutter pub get
      working-directory: ./src
      run: flutter pub get
    - name : flutter test
      working-directory: ./src
      run: flutter test
    - name : flutter build apk
      working-directory: ./src
      run: flutter build apk --debug --split-per-abi
    - name : flutter build ios --release --no-codesign
      working-directory: ./src
      run : flutter build ios --release --no-codesign
    - name: Push APK to Releases
      uses: ncipollo/release-action@v1
      with:
        working-directory: ./src
        artifacts: "build/app/outputs/apk/debug/*.apk"
        token: ${{ secrets.TOKEN }}
